### ISSUE TITLE
Issue with pulldown menu on small screens

### ISSUE THREAD

**Issue by sbaverett** [dmitrydwhite/pack-journal#30]
Because bootstrap expects that navigating to a link will take the user to a new page, the menu pulldown used on small screens doesn't close after the event. This makes for a clumsy user experience. We added a snippet of code to our project that provides a solution to this problem. Here it is in the event that you haven't addressed this issue already.

``` javascript
// https://github.com/twbs/bootstrap/issues/9013
$(document).on('click.nav', '.navbar-collapse.in', function(e) {
  if($(e.target).is('a') || $(e.target).is('button')) {
    $(this).collapse('hide');
  }
});
```

**Comment by mradamh** [comment]
thanks for the tip @sbaverett.  I don't think we are affected by this though.
